split:
  test_size: 0.2
  random_state: 2

scaling:
  enabled: true

model:
  type: "logistic_regression"  # Choose: logistic_regression, random_forest, svm
  n_estimators: 100
  random_state: 2
  kernel: "rbf"  # Only used for SVM
